/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 arrow.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'



export function Arrow(props) {
  const { nodes, materials } = useGLTF('models/arrow.glb')
  
  return (
    <group {...props} dispose={null}>
      <group position={[-0.35, 0.2, 0]} rotation={[-2, -1.49, -0.34]} scale={-0.03}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.dbl_Group_003} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.dbl_Group_002} />
      </group>
      <group position={[0.12, 0.27, 0]} rotation={[-2, -1.49, -0.34]} scale={-0.03}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['dbl_Group_002.001']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials.dbl_Group_004} />
      </group>
      <group position={[-0.35, 0.2, 0]} rotation={[1.15, 1.49, -2.8]} scale={0.03}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials['dbl_Group_003.001']} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials['dbl_Group_002.002']} />
      </group>
      <group position={[0.12, 0.27, 0]} rotation={[1.81, 1.49, 2.8]} scale={0.03}>
        <mesh geometry={nodes.Mesh003.geometry} material={materials.dbl_Group_001} />
        <mesh geometry={nodes.Mesh003_1.geometry} material={materials['dbl_Group_002.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/arrow.glb')
