/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 F2.gltf F3.gtlf F4.gltf F5.gltf F6.gltf F7.gltf F8.gltf F9.gltf F10.gltf
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function F2(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/F2.gltf')
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[10]].reset().fadeIn(0.5).play();
  }, []);
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Adventurer_Body">
            <skinnedMesh castShadow name="Cube051" geometry={nodes.Cube051.geometry} material={materials.Skin} skeleton={nodes.Cube051.skeleton} />
            <skinnedMesh castShadow name="Cube051_1" geometry={nodes.Cube051_1.geometry} material={materials.White} skeleton={nodes.Cube051_1.skeleton} />
            <skinnedMesh castShadow name="Cube051_2" geometry={nodes.Cube051_2.geometry} material={materials.Brown2} skeleton={nodes.Cube051_2.skeleton} />
            <skinnedMesh castShadow name="Cube051_3" geometry={nodes.Cube051_3.geometry} material={materials.LightGreen} skeleton={nodes.Cube051_3.skeleton} />
            <skinnedMesh castShadow name="Cube051_4" geometry={nodes.Cube051_4.geometry} material={materials.Gold} skeleton={nodes.Cube051_4.skeleton} />
            <skinnedMesh castShadow name="Cube051_5" geometry={nodes.Cube051_5.geometry} material={materials.Green} skeleton={nodes.Cube051_5.skeleton} />
          </group>
          <group name="Adventurer_Feet">
            <skinnedMesh castShadow name="Cube027" geometry={nodes.Cube027.geometry} material={materials.Brown_02} skeleton={nodes.Cube027.skeleton} />
            <skinnedMesh castShadow name="Cube027_1" geometry={nodes.Cube027_1.geometry} material={materials.Brown2} skeleton={nodes.Cube027_1.skeleton} />
          </group>
          <group name="Adventurer_Head">
            <skinnedMesh castShadow name="Cube032" geometry={nodes.Cube032.geometry} material={materials.Skin} skeleton={nodes.Cube032.skeleton} />
            <skinnedMesh castShadow name="Cube032_1" geometry={nodes.Cube032_1.geometry} material={materials.Hair_Brown} skeleton={nodes.Cube032_1.skeleton} />
            <skinnedMesh castShadow name="Cube032_2" geometry={nodes.Cube032_2.geometry} material={materials.Brown} skeleton={nodes.Cube032_2.skeleton} />
          </group>
          <group name="Adventurer_Legs">
            <skinnedMesh castShadow name="Cube052" geometry={nodes.Cube052.geometry} material={materials.Skin} skeleton={nodes.Cube052.skeleton} />
            <skinnedMesh castShadow name="Cube052_1" geometry={nodes.Cube052_1.geometry} material={materials.Brown_02} skeleton={nodes.Cube052_1.skeleton} />
            <skinnedMesh castShadow name="Cube052_2" geometry={nodes.Cube052_2.geometry} material={materials.White} skeleton={nodes.Cube052_2.skeleton} />
            <skinnedMesh castShadow name="Cube052_3" geometry={nodes.Cube052_3.geometry} material={materials.Brown2} skeleton={nodes.Cube052_3.skeleton} />
            <skinnedMesh castShadow name="Cube052_4" geometry={nodes.Cube052_4.geometry} material={materials.LightGreen} skeleton={nodes.Cube052_4.skeleton} />
            <skinnedMesh castShadow name="Cube052_5" geometry={nodes.Cube052_5.geometry} material={materials.Gold} skeleton={nodes.Cube052_5.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/F2.gltf')
