/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 F4.gltf
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function F4(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/F4.gltf')
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[4]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Formad_Head">
            <skinnedMesh castShadow name="Cube030" geometry={nodes.Cube030.geometry} material={materials.Skin} skeleton={nodes.Cube030.skeleton} />
            <skinnedMesh castShadow name="Cube030_1" geometry={nodes.Cube030_1.geometry} material={materials.Brown} skeleton={nodes.Cube030_1.skeleton} />
            <skinnedMesh castShadow name="Cube030_2" geometry={nodes.Cube030_2.geometry} material={materials.Red} skeleton={nodes.Cube030_2.skeleton} />
          </group>
          <group name="Formal_Body">
            <skinnedMesh castShadow name="Cube048" geometry={nodes.Cube048.geometry} material={materials.Skin} skeleton={nodes.Cube048.skeleton} />
            <skinnedMesh castShadow name="Cube048_1" geometry={nodes.Cube048_1.geometry} material={materials.LimeGreen} skeleton={nodes.Cube048_1.skeleton} />
            <skinnedMesh castShadow name="Cube048_2" geometry={nodes.Cube048_2.geometry} material={materials.Gold} skeleton={nodes.Cube048_2.skeleton} />
          </group>
          <group name="Formal_Feet">
            <skinnedMesh castShadow name="Cube047" geometry={nodes.Cube047.geometry} material={materials.Skin} skeleton={nodes.Cube047.skeleton} />
            <skinnedMesh castShadow name="Cube047_1" geometry={nodes.Cube047_1.geometry} material={materials.Red} skeleton={nodes.Cube047_1.skeleton} />
          </group>
          <group name="Formal_Legs">
            <skinnedMesh castShadow name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Skin} skeleton={nodes.Cube016.skeleton} />
            <skinnedMesh castShadow name="Cube016_1" geometry={nodes.Cube016_1.geometry} material={materials.LimeGreen} skeleton={nodes.Cube016_1.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/F4.gltf')
