/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 F5.gltf
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function F5(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/F5.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[14]].reset().fadeIn(0.5).play();
  }, []);

  useEffect(() => {
    const animationAction = actions[names[14]];
    animationAction.play();
    animationAction.paused = false;
    animationAction.time = 50 / animationAction.getClip().frameRate;
    animationAction.paused = true;
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Punk_Body">
            <skinnedMesh
              castShadow
              name="Cube049"
              geometry={nodes.Cube049.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube049.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube049_1"
              geometry={nodes.Cube049_1.geometry}
              material={materials.Pink}
              skeleton={nodes.Cube049_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube049_2"
              geometry={nodes.Cube049_2.geometry}
              material={materials.Black}
              skeleton={nodes.Cube049_2.skeleton}
            />
          </group>
          <group name="Punk_Feet">
            <skinnedMesh
              castShadow
              name="Cube050"
              geometry={nodes.Cube050.geometry}
              material={materials.Black}
              skeleton={nodes.Cube050.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube050_1"
              geometry={nodes.Cube050_1.geometry}
              material={materials.Grey}
              skeleton={nodes.Cube050_1.skeleton}
            />
          </group>
          <group name="Punk_Head">
            <skinnedMesh
              castShadow
              name="Cube031"
              geometry={nodes.Cube031.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube031.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube031_1"
              geometry={nodes.Cube031_1.geometry}
              material={materials.Pink}
              skeleton={nodes.Cube031_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube031_2"
              geometry={nodes.Cube031_2.geometry}
              material={materials.Black}
              skeleton={nodes.Cube031_2.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube031_3"
              geometry={nodes.Cube031_3.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Cube031_3.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube031_4"
              geometry={nodes.Cube031_4.geometry}
              material={materials.Brown}
              skeleton={nodes.Cube031_4.skeleton}
            />
          </group>
          <group name="Punk_Legs">
            <skinnedMesh
              castShadow
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube005.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube005_1"
              geometry={nodes.Cube005_1.geometry}
              material={materials.Black}
              skeleton={nodes.Cube005_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/F5.gltf");
