/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 F8.gltf
*/

import React, { useRef,useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function F8(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/F8.gltf')
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[4]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Suit_Body">
            <skinnedMesh castShadow name="Cube034" geometry={nodes.Cube034.geometry} material={materials.Skin} skeleton={nodes.Cube034.skeleton} />
            <skinnedMesh castShadow name="Cube034_1" geometry={nodes.Cube034_1.geometry} material={materials.Black} skeleton={nodes.Cube034_1.skeleton} />
            <skinnedMesh castShadow name="Cube034_2" geometry={nodes.Cube034_2.geometry} material={materials.White} skeleton={nodes.Cube034_2.skeleton} />
          </group>
          <group name="Suit_Feet">
            <skinnedMesh castShadow name="Cube053" geometry={nodes.Cube053.geometry} material={materials.Skin} skeleton={nodes.Cube053.skeleton} />
            <skinnedMesh castShadow name="Cube053_1" geometry={nodes.Cube053_1.geometry} material={materials.Black} skeleton={nodes.Cube053_1.skeleton} />
          </group>
          <group name="Suit_Head">
            <skinnedMesh castShadow name="Cube033" geometry={nodes.Cube033.geometry} material={materials.Skin} skeleton={nodes.Cube033.skeleton} />
            <skinnedMesh castShadow name="Cube033_1" geometry={nodes.Cube033_1.geometry} material={materials.Hair_Brown} skeleton={nodes.Cube033_1.skeleton} />
            <skinnedMesh castShadow name="Cube033_2" geometry={nodes.Cube033_2.geometry} material={materials.Brown} skeleton={nodes.Cube033_2.skeleton} />
            <skinnedMesh castShadow name="Cube033_3" geometry={nodes.Cube033_3.geometry} material={materials.Hair_Blond} skeleton={nodes.Cube033_3.skeleton} />
          </group>
          <skinnedMesh castShadow name="Suit_Legs" geometry={nodes.Suit_Legs.geometry} material={materials.Black} skeleton={nodes.Suit_Legs.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/F8.gltf')
