/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Female1.gltf
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Female1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/Female1.gltf");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[4]].reset().fadeIn(0.5).play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Casual_Body">
            <skinnedMesh
              castShadow
              name="Cube037"
              geometry={nodes.Cube037.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube037.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube037_1"
              geometry={nodes.Cube037_1.geometry}
              material={materials.White}
              skeleton={nodes.Cube037_1.skeleton}
            />
          </group>
          <group name="Casual_Feet">
            <skinnedMesh
              castShadow
              name="Cube070"
              geometry={nodes.Cube070.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube070.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube070_1"
              geometry={nodes.Cube070_1.geometry}
              material={materials.Grey}
              skeleton={nodes.Cube070_1.skeleton}
            />
          </group>
          <group name="Casual_Head">
            <skinnedMesh
              castShadow
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube001_1"
              geometry={nodes.Cube001_1.geometry}
              material={materials.Hair_Brown}
              skeleton={nodes.Cube001_1.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube001_2"
              geometry={nodes.Cube001_2.geometry}
              material={materials.Brown}
              skeleton={nodes.Cube001_2.skeleton}
            />
            <skinnedMesh
              castShadow
              name="Cube001_3"
              geometry={nodes.Cube001_3.geometry}
              material={materials.Hair_Blond}
              skeleton={nodes.Cube001_3.skeleton}
            />
          </group>
          <skinnedMesh
            castShadow
            name="Casual_Legs"
            geometry={nodes.Casual_Legs.geometry}
            material={materials.Orange}
            skeleton={nodes.Casual_Legs.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Female1.gltf");
